#version: "3.9"
services:
  kong:
    image: kong/kong-gateway:3.7
    container_name: kong
    volumes:
      - ./configs/kong.yaml:/config/kong.yaml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/config/kong.yaml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_STATUS_LISTEN=0.0.0.0:8100
      - KONG_TRACING_INSTRUMENTATIONS=all
      - KONG_TRACING_SAMPLING_RATE=1.0
      - KONG_LICENSE_DATA
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    networks:
      - kong-obs

  fluentbit:
    image: fluent/fluent-bit:3.1.2
    container_name: fluentbit
    command:
      - --config=/fluent-bit/etc/fluent-bit.yaml
    networks:
      - kong-obs
    volumes:
      - ./configs/fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    container_name: otel-collector
    networks:
      - kong-obs
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
    command: ["-config.file=/etc/tempo.yaml"]
    restart: unless-stopped
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
      - "9411:9411"
    networks:
      - kong-obs

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=otlp-write-receiver
    ports:
      - "9090:9090"
    sysctls:
      net.core.somaxconn: 511
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kong-obs

  loki-read:
    image: grafana/loki:3.0.0
    command:
      - -config.file=/mnt/config/loki-config.yaml
      - -target=read
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./configs/loki-config.yaml:/mnt/config/loki-config.yaml
    networks:
      kong-obs:
        aliases:
          - loki-read

  loki-write:
    image: grafana/loki:3.0.0
    command:
      - -config.file=/mnt/config/loki-config.yaml
      - -target=write
    ports:
      - 3102:3100
      - 7946
      - 9095
    volumes:
      - ./configs/loki-config.yaml:/mnt/config/loki-config.yaml
    networks:
      kong-obs:
        aliases:
          - loki-write
  loki-backend:
    image: grafana/loki:3.0.0
    command:
      - -config.file=/mnt/config/loki-config.yaml
      - -target=backend
    ports:
      - 3103:3100
      - 7946
      - 9095
    volumes:
      - ./configs/loki-config.yaml:/mnt/config/loki-config.yaml
    networks:
      kong-obs:
        aliases:
          - loki-backend
  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards/
    ports:
      - "3000:3000"
    networks:
      - kong-obs

  hotrod:
    image: jaegertracing/example-hotrod:1.57
    container_name: hotrod
    command: ["all"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - kong-obs

networks:
  kong-obs:
    driver: bridge